name: sstranswaysindia
description: "SS Transways India - Transportation Management App for tracking trips, attendance, and fleet operations."
publish_to: 'none'

version: 1.0.163+163

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  intl: ^0.19.0
  lottie: ^3.3.1
  url_launcher: ^6.3.0
  google_fonts: ^6.2.1
  just_audio: ^0.9.36
  file_picker: ^8.0.7
  flutter_tts: ^3.8.3
  image_picker: ^1.0.7
  path_provider: ^2.1.3
  path: ^1.9.0
  geolocator: ^10.1.0
  flutter_local_notifications: ^19.4.2
  permission_handler: ^11.4.0
  timezone: ^0.10.1
  share_plus: ^7.2.1
  in_app_update: ^4.2.0
  image: ^4.1.7
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2
  device_info_plus: ^10.1.0
  webview_flutter: ^4.4.2
  package_info_plus: ^9.0.0
  mime: ^1.0.4
  google_mobile_ads: ^5.1.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.18
  cupertino_icons: ^1.0.8
  pdf: ^3.11.3
  wakelock_plus: ^1.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/blue_loading.json
    - assets/animations/check_mark_success.json
    - assets/animations/notification.json
    - assets/animations/green_flashing_circle_icon.json
    - assets/animations/man_account_icon.json
    - downloads/welcome.json
    - downloads/face_biometric.json
    - downloads/Checkin.json
    - downloads/Checkout.json
    - downloads/
