// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBejHuXwznikJd20U23HQP_uGaJepCTc2g',
    appId: '1:772073583253:web:141f309e9793efa511219c',
    messagingSenderId: '772073583253',
    projectId: 'sstranswaysindia-26d47',
    authDomain: 'sstranswaysindia-26d47.firebaseapp.com',
    storageBucket: 'sstranswaysindia-26d47.firebasestorage.app',
    measurementId: 'G-377EEKXZFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWbyi29RicZg6ONTnwpDp75oEUW9C5q_E',
    appId: '1:772073583253:android:6f238fce3e38062d11219c',
    messagingSenderId: '772073583253',
    projectId: 'sstranswaysindia-26d47',
    storageBucket: 'sstranswaysindia-26d47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBejHuXwznikJd20U23HQP_uGaJepCTc2g',
    appId: '1:772073583253:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '772073583253',
    projectId: 'sstranswaysindia-26d47',
    storageBucket: 'sstranswaysindia-26d47.firebasestorage.app',
    iosBundleId: 'com.example.sstranswaysindia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBejHuXwznikJd20U23HQP_uGaJepCTc2g',
    appId: '1:772073583253:ios:YOUR_MACOS_APP_ID',
    messagingSenderId: '772073583253',
    projectId: 'sstranswaysindia-26d47',
    storageBucket: 'sstranswaysindia-26d47.firebasestorage.app',
    iosBundleId: 'com.example.sstranswaysindia',
  );
}
